name: Draw pipeline

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Do Nothing
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2