name: deploy-to-prod

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: enigmind/Escabot@main
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: whoami
